on:
  issues:
    types:
      - opened
      
jobs:
  label_issue:
    runs-on: ubuntu-latest
    steps:
      - name: Set label
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
        run: |
          gh issue edit $ISSUE_URL --add-label "triage"
    
      - name: Echo event context 
      - env:
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
        run: |
          echo $EVENT_CONTEXT
 
