on:
  issues:
    types:
      - opened
      
jobs:
  label_issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Set label
      - run: |
          gh issue edit $ISSUE_URL --add-label "triage"
          echo $EVENT_CONTEXT
      - env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ISSUE_URL: ${{ github.event.issue.html_url }}
          EVENT_CONTEXT: ${{ toJSON(github.event) }}
          
 
    
