on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

      
jobs:
  label_issue:
    runs-on: ubuntu-latest
    
    steps:
      - name: Say Hello  
        run: |
          echo Hello $NAME!
          echo -in $HOME
        env:
          NAME: ${{ github.event.inputs.name }}
          HOME: ${{ github.event.inputs.home }}
          
 
  call-workflow-1-in-local-repo:
    uses: pkskelly/actiontests/.github/workflows/reusable.yml@main
    with:
      username: 'Pete'
    
