name: Reusable workflow example

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  example_job:
    name: Passed input and secrets 
    runs-on: ubuntu-latest
    steps:
      - name: Say Hello  
        run: |
          echo Hello ${{ inputs.username }} with totken ${{ secrets.token }}!  
